"""The basic inference primitive.

A `Generator` owns a live `(state, last_input, key, done)` and exposes a
single method, `advance(max_steps, stop_when=None)`, that runs the
autoregressive loop and returns the strokes generated by *this* call. Both
the multi-line `Hand.write` facade and the single-line streaming facade are
implemented as thin layers over this class.
"""

from __future__ import annotations

from typing import Callable

import mlx.core as mx
import numpy as np

from .model import ALPHABET_SIZE, HandwritingCell

EVAL_EVERY = 8

StopPredicate = Callable[[np.ndarray, np.ndarray], np.ndarray]
"""Signature: `(phi_np, last_stroke_np) -> [B] bool`. True means stop sample."""


class Generator:
    def __init__(
        self,
        cell: HandwritingCell,
        chars: np.ndarray,
        char_lengths: np.ndarray,
        biases: np.ndarray,
        x_prime: np.ndarray | None = None,
        prime_lengths: np.ndarray | None = None,
        seed: int = 0,
    ):
        self._cell = cell
        self._char_lengths = char_lengths.astype(np.int32)
        self._batch_size, self._max_char_length = chars.shape

        chars_index = mx.array(chars.astype(np.int32))
        self._chars_onehot = mx.take(mx.eye(ALPHABET_SIZE, dtype=mx.float32), chars_index, axis=0)
        self._char_positions = mx.arange(self._max_char_length, dtype=mx.float32).reshape(
            1, 1, self._max_char_length
        )
        within_length = mx.arange(self._max_char_length, dtype=mx.int32).reshape(1, self._max_char_length) < mx.array(
            self._char_lengths
        ).reshape(-1, 1)
        self._char_mask = mx.expand_dims(within_length.astype(mx.float32), 2)
        self._bias_per_sample = mx.array(biases.astype(np.float32))

        self._state = cell.initial_state(self._batch_size, self._max_char_length)
        self._last_input = mx.broadcast_to(
            mx.array([[0.0, 0.0, 1.0]], dtype=mx.float32), (self._batch_size, 3)
        )
        self._key = mx.random.key(int(seed))
        self._done = np.zeros((self._batch_size,), dtype=bool)
        self._step_function = self._compile_step()

        if x_prime is not None and prime_lengths is not None and int(prime_lengths.max()) > 0:
            self._run_priming(x_prime, prime_lengths)

    def _compile_step(self):
        cell = self._cell

        @mx.compile
        def step(state, inputs, chars_onehot, char_positions, char_mask, bias_per_sample, key):
            new_state = cell.step(state, inputs, chars_onehot, char_positions, char_mask)
            next_inputs = cell.head.sample(new_state[4], bias_per_sample, key)
            return new_state, next_inputs

        return step

    def _run_priming(self, x_prime: np.ndarray, prime_lengths: np.ndarray) -> None:
        cell = self._cell
        max_prime = int(prime_lengths.max())
        prime_strokes = mx.array(x_prime[:, :max_prime, :].astype(np.float32))
        prime_lengths_mx = mx.array(prime_lengths.astype(np.int32))

        @mx.compile
        def prime_step(state, inputs, chars_onehot, char_positions, char_mask):
            return cell.step(state, inputs, chars_onehot, char_positions, char_mask)

        for time_index in range(max_prime):
            new_state = prime_step(
                self._state,
                prime_strokes[:, time_index, :],
                self._chars_onehot,
                self._char_positions,
                self._char_mask,
            )
            still_priming = mx.expand_dims(
                (mx.array(np.array([time_index], dtype=np.int32)) < prime_lengths_mx).astype(mx.float32), 1
            )
            self._state = tuple(mx.where(still_priming, new, old) for new, old in zip(new_state, self._state))
            if (time_index + 1) % EVAL_EVERY == 0:
                mx.eval(self._state)
        mx.eval(self._state)

        # First free-run input is sampled from the primed state — matches the
        # upstream `rnn_free_run(initial_input=None)` path.
        self._key, sample_key = mx.random.split(self._key, 2)
        self._last_input = cell.head.sample(self._state[4], self._bias_per_sample, sample_key)
        mx.eval(self._last_input)

    @property
    def done(self) -> np.ndarray:
        return self._done

    def advance(
        self, max_steps: int, stop_when: StopPredicate | None = None
    ) -> np.ndarray:
        """Run up to `max_steps` more steps and return the strokes produced.

        Returned shape is `[B, T_actual, 3]` with zeros in rows where the
        corresponding sample had already terminated. The internal state is
        mutated; the next `advance` call resumes seamlessly.
        """
        if self._done.all():
            return np.zeros((self._batch_size, 0, 3), dtype=np.float32)

        emitted_strokes: list[np.ndarray] = []
        pending: list[tuple[mx.array, mx.array]] = []  # (next_inputs, phi)

        for _ in range(max_steps):
            self._key, step_key = mx.random.split(self._key, 2)
            new_state, next_inputs = self._step_function(
                self._state,
                self._last_input,
                self._chars_onehot,
                self._char_positions,
                self._char_mask,
                self._bias_per_sample,
                step_key,
            )
            active = mx.expand_dims(mx.array((~self._done).astype(np.float32)), 1)
            self._state = tuple(mx.where(active, new, old) for new, old in zip(new_state, self._state))
            next_inputs = next_inputs * active
            self._last_input = next_inputs

            pending.append((next_inputs, self._state[8]))

            if len(pending) >= EVAL_EVERY:
                if self._flush(pending, emitted_strokes, stop_when):
                    break
                pending = []

        if pending:
            self._flush(pending, emitted_strokes, stop_when)

        if not emitted_strokes:
            return np.zeros((self._batch_size, 0, 3), dtype=np.float32)
        return np.stack(emitted_strokes, axis=1)

    def _flush(
        self,
        pending: list[tuple[mx.array, mx.array]],
        emitted_strokes: list[np.ndarray],
        stop_when: StopPredicate | None,
    ) -> bool:
        """Eagerly evaluate buffered steps, append to outputs, update done.

        Returns True when the loop should stop (all done, or `stop_when`
        signals stop for every still-active sample).
        """
        mx.eval(*(stroke for stroke, _ in pending), *(phi for _, phi in pending))
        for stroke_array, phi_array in pending:
            stroke_np = np.array(stroke_array)
            phi_np = np.array(phi_array)
            emitted_strokes.append(stroke_np)

            char_at_attention = phi_np.argmax(axis=1)
            eos = stroke_np[:, 2]
            past_final = char_at_attention >= self._char_lengths
            final_with_eos = (char_at_attention >= self._char_lengths - 1) & (eos == 1.0)
            self._done = self._done | past_final | final_with_eos

            if stop_when is not None:
                stop_mask = stop_when(phi_np, stroke_np)
                if (stop_mask | self._done).all():
                    return True

            if self._done.all():
                return True
        return False
